global:
  scrape_interval: 5s   
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gin_backend'  
    static_configs:
      - targets: ['backend:8080']
    labels:
      service: 'ylia-backend'
      environment: 'production'
    scrape_timeout: 10s
    metrics_path: /metrics